#!/bin/sh
#
# @name Coaxial Hexadecacopter X geometry (16 rotors)
#
# @type Octorotor Coaxial
# @class Copter
#
# @output Motor 1  Upper
# @output Motor 2  Upper
# @output Motor 3  Upper
# @output Motor 4  Upper
# @output Motor 5  Upper
# @output Motor 6  Upper
# @output Motor 7  Upper
# @output Motor 8  Upper
# @output Motor 9  Lower (under M1)
# @output Motor 10 Lower (under M2)
# @output Motor 11 Lower (under M3)
# @output Motor 12 Lower (under M4)
# @output Motor 13 Lower (under M5)
# @output Motor 14 Lower (under M6)
# @output Motor 15 Lower (under M7)
# @output Motor 16 Lower (under M8)
#
# @maintainer PX4 Development Team
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 14

# Enable PWM output on all 14 timers (400Hz)
param set-default PWM_MAIN_TIM0 400
param set-default PWM_MAIN_TIM1 400
param set-default PWM_MAIN_TIM2 400
param set-default PWM_MAIN_TIM3 400
param set-default PWM_MAIN_TIM4 400
param set-default PWM_MAIN_TIM5 400
param set-default PWM_MAIN_TIM6 400
param set-default PWM_MAIN_TIM7 400
param set-default PWM_MAIN_TIM8 400
param set-default PWM_MAIN_TIM9 400
param set-default PWM_MAIN_TIM10 400
param set-default PWM_MAIN_TIM11 400
param set-default PWM_MAIN_TIM12 400
param set-default PWM_MAIN_TIM13 400

# Motor to channel mapping (Motor X -> output function 10X)
param set-default PWM_MAIN_FUNC1 102
param set-default PWM_MAIN_FUNC2 110
param set-default PWM_MAIN_FUNC3 109
param set-default PWM_MAIN_FUNC4 115
param set-default PWM_MAIN_FUNC5 112
param set-default PWM_MAIN_FUNC6 114
param set-default PWM_MAIN_FUNC7 101
param set-default PWM_MAIN_FUNC8 106
param set-default PWM_MAIN_FUNC9 105
param set-default PWM_MAIN_FUNC10 113
param set-default PWM_MAIN_FUNC11 103
param set-default PWM_MAIN_FUNC12 107
param set-default PWM_MAIN_FUNC13 108
param set-default PWM_MAIN_FUNC14 111
param set-default PWM_MAIN_FUNC15 116
param set-default PWM_MAIN_FUNC16 104

param set-default CA_ROTOR_COUNT 16

# Upper M1
param set-default CA_ROTOR0_PX 0.46
param set-default CA_ROTOR0_PY 0.19
param set-default CA_ROTOR0_PZ -0.05
param set-default CA_ROTOR0_KM -0.05

# Upper M2
param set-default CA_ROTOR1_PX -0.46
param set-default CA_ROTOR1_PY -0.19
param set-default CA_ROTOR1_PZ -0.05
param set-default CA_ROTOR1_KM -0.05

# Upper M3
param set-default CA_ROTOR2_PX 0.19
param set-default CA_ROTOR2_PY 0.46
param set-default CA_ROTOR2_PZ -0.05

# Upper M4
param set-default CA_ROTOR3_PX -0.46
param set-default CA_ROTOR3_PY 0.19
param set-default CA_ROTOR3_PZ -0.05

# Upper M5
param set-default CA_ROTOR4_PX 0.46
param set-default CA_ROTOR4_PY -0.19
param set-default CA_ROTOR4_PZ -0.05

# Upper M6
param set-default CA_ROTOR5_PX -0.19
param set-default CA_ROTOR5_PY -0.46
param set-default CA_ROTOR5_PZ -0.05

# Upper M7
param set-default CA_ROTOR6_PX 0.19
param set-default CA_ROTOR6_PY -0.46
param set-default CA_ROTOR6_PZ -0.05
param set-default CA_ROTOR6_KM -0.05

# Upper M8
param set-default CA_ROTOR7_PX -0.19
param set-default CA_ROTOR7_PY 0.46
param set-default CA_ROTOR7_PZ -0.05
param set-default CA_ROTOR7_KM -0.05

# Lower M9 (under M1)
param set-default CA_ROTOR8_PX 0.46
param set-default CA_ROTOR8_PY 0.19
param set-default CA_ROTOR8_PZ 0.05
param set-default CA_ROTOR8_KM 0.05

# Lower M10 (under M2)
param set-default CA_ROTOR9_PX -0.46
param set-default CA_ROTOR9_PY -0.19
param set-default CA_ROTOR9_PZ 0.05
param set-default CA_ROTOR9_KM 0.05

# Lower M11 (under M3)
param set-default CA_ROTOR10_PX 0.19
param set-default CA_ROTOR10_PY 0.46
param set-default CA_ROTOR10_PZ 0.05
param set-default CA_ROTOR10_KM -0.05

# Lower M12 (under M4)
param set-default CA_ROTOR11_PX -0.46
param set-default CA_ROTOR11_PY 0.19
param set-default CA_ROTOR11_PZ 0.05
param set-default CA_ROTOR11_KM -0.05

# Lower M13 (under M5)
param set-default CA_ROTOR12_PX 0.46
param set-default CA_ROTOR12_PY -0.19
param set-default CA_ROTOR12_PZ 0.05
param set-default CA_ROTOR12_KM -0.05

# Lower M14 (under M6)
param set-default CA_ROTOR13_PX -0.19
param set-default CA_ROTOR13_PY -0.46
param set-default CA_ROTOR13_PZ 0.05
param set-default CA_ROTOR13_KM -0.05

# Lower M15 (under M7)
param set-default CA_ROTOR14_PX 0.19
param set-default CA_ROTOR14_PY -0.46
param set-default CA_ROTOR14_PZ 0.05
param set-default CA_ROTOR14_KM 0.05

# Lower M16 (under M8)
param set-default CA_ROTOR15_PX -0.19
param set-default CA_ROTOR15_PY 0.46
param set-default CA_ROTOR15_PZ 0.05
param set-default CA_ROTOR15_KM 0.05


